# Generated by Django 6.0.1 on 2026-01-18 17:22

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifies',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications_genre', to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='classifies',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications_movie', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(storage=storages.backends.s3.S3Storage, upload_to='images/'),
        ),
    ]
