# Generated by Django 6.0.1 on 2026-01-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_classifies_genre_id_alter_classifies_movie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(help_text='Genres to which the movie belongs', related_name='movies', through='movies.Classifies', to='movies.genre'),
        ),
    ]
