# Generated by Django 6.0.1 on 2026-01-19 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieshow',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='movieshow',
            name='cinema_id',
        ),
        migrations.AddField(
            model_name='movieshow',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CinemaRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('rows', models.JSONField()),
                ('seats_per_row', models.PositiveBigIntegerField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema', to='movies.cinema')),
            ],
        ),
        migrations.AddField(
            model_name='movieshow',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='movies.cinemaroom'),
        ),
    ]
