# Generated by Django 6.0.1 on 2026-01-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movieshow_available_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='total_seats',
        ),
        migrations.AlterField(
            model_name='movieshow',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='movies.cinemaroom'),
        ),
    ]
